File Transfer Assignment part 2
Folders, txt files created.
after testing code, recieved error:
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

in reference to line 42.. which doesn't have anything  on it. Please seek assistance on this issue.